### ISSUE TITLE
Count is ignored when running search

### ISSUE THREAD

**Issue by rcazangi** [FHIR/fhir.js#101]
I tried to use count so that I can control the page size on my searches but it was ignored.

Here's what I did:
```javascript
client.search({
    type: resource,
    query: query,
    count: 5
});
```
While debugging, I found that '_count' does get added to property params but NOT to the URL.

Not sure it's a bug or if I'm doing something wrong. Couldn't find documentation for this.

As a workaround, I added { _count: 5 } directly to the query.

**Comment by mike1pol** [comment]
Hi.
It not a bug, you need to use `_count` or `_limit` like in [FHIR search](https://www.hl7.org/fhir/search.html)
