### ISSUE TITLE
pagination links - "previous" vs. "prev"

### ISSUE THREAD

**Issue by cah-ricksuggs** [FHIR/fhir.js#105]
I'm using this with the "Smart Health IT Sandbox" https://sandbox.smarthealthit.org/smartdstu2 and noticed that the paginated responses from that service are returning pagination links with the key: "previous" while this library is preconfigured to look for "prev". Is there any way to customize that?

Thanks

**Comment by niquola** [comment]
Hi, patch is welcome :)

**Comment by akanduru** [comment]
As per https://www.iana.org/assignments/link-relations/link-relations.xhtml#link-relations-1 (this is the definition FHIR bundle is referring to), it looks like both prev and previous are valid in link.relation. I don't think it is a great idea, but it is what it is. Would you please entertain a pull request if I patch it up to work with both?

**Comment by ricksuggs** [comment]
This can be closed because this PR was merged: https://github.com/FHIR/fhir.js/pull/111

**Comment by jmandel** [comment]
Thanks!
