### ISSUE TITLE
Update package "request" to avoid vulnerabilities

### ISSUE THREAD

**Issue by plynchnlm** [FHIR/fhir.js#108]
The version of "request" being used (2.42.0) has several vulnerabilities on itself (https://nodesecurity.io/advisories/309) and its sub-packages, and needs to be updated.  Unfortunately, doing so causes two tests in nodeAdapterSpec.js to fail, so it will require some adjustment to the code.  I debugged a little, and noticed that src/adapters/node.js includes several non-standard keys on the args (options) object it passed to "request", which might (or might not) be the issue.

**Comment by plynchnlm** [comment]
This was fixed by the recent merge of a pull request, but a new version needs to be tagged for npm to pick up the fix.

**Comment by akanduru** [comment]
@niquola: Would you please tag and update bower-fhir package as well?
