### ISSUE TITLE
Missing defer property in Adapter object of native.js

### ISSUE THREAD

**Issue by kugoo109** [FHIR/fhir.js#119]
Hi, I encounter a problem while using native adapter. There is no defer property in the Native adapter.
Hope to see the new release including this hotfix.

Below is the detail of the error:
`Uncaught TypeError: adapter.defer is not a function`

Here is the way I manually fix it but not persist after npm get new updates. 
```
// Build Adapter Object
var adapter = {
  defer: defer, // <--- missing property
  http: function (args) {
```

**Comment by niquola** [comment]
Can you PR this fix?
