### ISSUE TITLE
Fix integration tests

### ISSUE THREAD

**Issue by akanduru** [FHIR/fhir.js#126]
`npm run integrate` fails due to non-availability of FHIR server for testing. There is also an assertion failure on generated family name. I intend to send a PR to fix the tests by switching test FHIR server to more reliable http://hapi.fhir.org?. I will also address issue #108 in my PR. The changes will include PR#113 and PR#125.

**Comment by niquola** [comment]
it’s better to use movk fhir server for tests

**Comment by akanduru** [comment]
Not sure what movk mean? Can you specify the URL?

**Comment by mike1pol** [comment]
i think @niquola talk about mock

**Comment by akanduru** [comment]
Oh, yea I agree! 

If I am dong it, that might be another PR...
