### ISSUE TITLE
NPM version last published 2 years ago?

### ISSUE THREAD

**Issue by bradenhs** [FHIR/fhir.js#128]
I noticed the NPM distribution of this library was last published 2 years ago:

<img width="400" alt="screen shot 2018-10-24 at 4 31 03 pm" src="https://user-images.githubusercontent.com/22484684/47459520-4d887200-d7aa-11e8-9a96-4afe3d8f161f.png">

However, it appears the project is being updated more frequently than that. What is the recommended way to get the code? NPM or just cloning and using the source directly?

**Comment by mike1pol** [comment]
v0.1.0 in progress, you can help us by closing some issue from [v0.1.0 milestone](https://github.com/FHIR/fhir.js/milestone/4)
