### ISSUE TITLE
More documentation on others methods

### ISSUE THREAD

**Issue by CodeAndChoke** [FHIR/fhir.js#139]
Hi,

I really like your library and would love to apply it to our CS software project. However I cann't find any documentation about how to update/delete/patch... etc. Is there any hint where I could start? 

thank you

**Comment by longnguyen2306** [comment]
Following is an update of readme that I find useful. If you guys think that is okay and need some more help, I will be ready to write more documentation in the next time.

**Comment by joeldenning** [comment]
👍 I am also interested in helping out with this. I just added #147 which documents the `fhir.read()` function.
