### ISSUE TITLE
Interested in a YUI adapter?

### ISSUE THREAD

**Issue by colmbrady** [FHIR/fhir.js#35]
Im interested in contributing a YUI adapter for fhir.js. Would you be interested in accepting a pull request for this?

**Comment by niquola** [comment]
Yes, surely. You are welcome. If any questions - just contact (https://plus.google.com/u/0/+%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9%D0%A0%D1%8B%D0%B6%D0%B8%D0%BA%D0%BE%D0%B2/posts).

**Comment by colmbrady** [comment]
Have created an adapter here https://github.com/colmbrady/fhir.js/tree/yui-adapter and added integration tests that match the JQ adapter. Note the angular tests seemed broken.

**Comment by niquola** [comment]
Perfect!

Could you send pull-request - i will merge

thx, i will check angularjs tests

73's nicola
