### ISSUE TITLE
Create/Update

### ISSUE THREAD

**Issue by taramoskam** [FHIR/fhir.js#41]
Hello, I've been working with your library in nodejs.

I've successfully got read and search working, however create and update consistently give the error "id = headers('Content-Location') ---- typeError: undefined is not a function", (found in resource.js)  I have attempted to change id = headers && headers('Content-Location') || ?? like the read function, which produced a 'Content-Type' hasn't been declared error for update. I put the content-type in headers as well which led to a can not parse JSON error. Finally I retrieved the patient object which would update in my console but not on the server. (I'm using UHN's). I would greatly appreciate some assistance!

This is my entry:
var entry =
{
	category: [{term: 'TAG term', schema: 'TAG schema', label: 'TAG label'}],
	content: 
	{
			resourceType: "Patient",
			name: 
			[
			{
				family: ["Bob"],
				given: ["Smith"]
			}
			],
			birthDate: '1990-06-20'	
	}
};

this is my create statement:
var test = client.create(entry, function(err, entry)
{
	console.log(entry.id);
	console.log(err);
});

this is how I instantiate the client:
var client = new mkFhir({
	baseUrl: 'http://fhirtest.uhn.ca/baseDstu1'
	});

**Comment by niquola** [comment]
Hi, which node version do you use?

**Comment by taramoskam** [comment]
I'm out of office now but I can check in the morning. I'm certain I have the latest version I just downloaded it.

**Comment by taramoskam** [comment]
Hello, I'm still having issues with the create/update functions. Now either: 

 client.update(ptUpdate, function (err, res)
{
	console.log(res);
	console.log(err);
});

with: 

var ptUpdate = {
	id: "http://fhirtest.uhn.ca/baseDstu1/Patient/35287",
  content: {
    resourceType: 'Patient',
    birthDate: '1990-06-20'
  }
};

or :

client.create(new_pt, function(err, res)
{
	console.log(res);
	console.log(err);
});

with 

var new_pt= {
  content: {
    resourceType: 'Patient',
name: 
			[
			{
				family: ["Bob"],
				given: ["Smith"]
			}
			],
    birthDate: '1990-06-20'
  }
};

both give the same error when implementing the fixes to the node adapter. 

in resource.js, return cb({ --- TypeError: undefined is not a function
