### ISSUE TITLE
DSTU2 updates

### ISSUE THREAD

**Issue by nschwertner** [FHIR/fhir.js#46]
This commit updates the pagination code with DSTU2:
https://github.com/smart-on-fhir/fhir.js/commit/7407ed4ac780c967a247a29252da7efe0a2b2741

I see that there is a `dstu2` branch in the repo already, but seems out of date with the latest code. Could we get the `dstu2` branch up to speed so that we can merge this in?

**Comment by niquola** [comment]
Let's use master as dstu2 branch
