### ISSUE TITLE
Can't express repeat search parameters in fhir.js

### ISSUE THREAD

**Issue by nschwertner** [FHIR/fhir.js#51]
I am trying to express the following FHIR query:
`/Patient?_sort:asc=given&_sort:asc=family&_count=25`
in the fhir.js search syntax, but am having trouble. At first sight, it looks like the following would produce the desired result:
`{type: 'Patient', query: {'_sort:asc':['given', 'family'], _count:25}}`
but that does not work. What am I missing here?

**Comment by niquola** [comment]
https://github.com/FHIR/fhir.js/blob/master/test/querySpec.coffee#L66

**Comment by nschwertner** [comment]
Ah, missed that one. Thank you
