### ISSUE TITLE
Webpack reports "the request of a dependency is an expression" in /request/lib/optional.js 9:13-32

### ISSUE THREAD

**Issue by developer-x** [FHIR/fhir.js#55]
Hi,

I'm seeing the following errors when integrating fhir.js into a React app and running webpack:

WARNING in ./~/fhir.js/~/request/lib/optional.js
Critical dependencies:
9:13-32 the request of a dependency is an expression
 @ ./~/fhir.js/~/request/lib/optional.js 9:13-32

ERROR in ./~/fhir.js/~/request/request.js
Module not found: Error: Cannot resolve module 'net' in /Users/andrewhall/Documents/fihr-store/node_modules/fhir.js/node_modules/request
 @ ./~/fhir.js/~/request/request.js 33:10-24

ERROR in ./~/tunnel-agent/index.js
Module not found: Error: Cannot resolve module 'net' in /Users/andrewhall/Documents/fihr-store/node_modules/tunnel-agent
 @ ./~/tunnel-agent/index.js 3:10-24

ERROR in ./~/tunnel-agent/index.js
Module not found: Error: Cannot resolve module 'tls' in /Users/andrewhall/Documents/fihr-store/node_modules/tunnel-agent
 @ ./~/tunnel-agent/index.js 4:10-24

ERROR in ./~/fhir.js/~/forever-agent/index.js
Module not found: Error: Cannot resolve module 'net' in /Users/andrewhall/Documents/fihr-store/node_modules/fhir.js/node_modules/forever-agent
 @ ./~/fhir.js/~/forever-agent/index.js 6:10-24

ERROR in ./~/fhir.js/~/forever-agent/index.js
Module not found: Error: Cannot resolve module 'tls' in /Users/andrewhall/Documents/fihr-store/node_modules/fhir.js/node_modules/forever-agent
 @ ./~/fhir.js/~/forever-agent/index.js 7:10-24

ERROR in ./~/fhir.js/~/mime-types/lib/custom.json
Module parse failed: /Users/andrewhall/Documents/fihr-store/node_modules/fhir.js/node_modules/mime-types/lib/custom.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "text/jade": [
|     "jade"
|   ],
 @ ./~/fhir.js/~/mime-types/lib/index.js 13:10-34

ERROR in ./~/fhir.js/~/mime-types/lib/node.json
Module parse failed: /Users/andrewhall/Documents/fihr-store/node_modules/fhir.js/node_modules/mime-types/lib/node.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "text/vtt": [
|     "vtt"
|   ],
 @ ./~/fhir.js/~/mime-types/lib/index.js 12:8-30

ERROR in ./~/fhir.js/~/mime-types/lib/mime.json
Module parse failed: /Users/andrewhall/Documents/fihr-store/node_modules/fhir.js/node_modules/mime-types/lib/mime.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "application/1d-interleaved-parityfec": [],
|   "application/3gpp-ims+xml": [],
|   "application/activemessage": [],
 @ ./~/fhir.js/~/mime-types/lib/index.js 11:8-30

Any ideas?

**Comment by niquola** [comment]
Could you show your webpack config?

**Comment by developer-x** [comment]
module.exports = {
    entry: './app/components/main.js',
    output: {
        filename: 'public/bundle.js'
    },
    module: {
        loaders: [
            {
                test: /\.jsx?$/,
                exclude: /(node_modules|bower_components)/,
                loader: 'babel'
            }
        ]
    }
}

**Comment by niquola** [comment]
And how do you "requires" fhir.js in your code?

**Comment by developer-x** [comment]
I've wrapped fhir inside a ES6 class and use import - here is the code

import fhir from "fhir.js"
    
    // Composite Class for the FHIR client.  This will add wrappers to return promises for all calls to the FHIR Client
    //
    export default class FHIRClient {
    
        constructor(opts) {
            this._fhirClient = fhir(opts);
            var fhirClient = this._fhirClient;
    
            // Build Composite method to return promise
            //
            ["search", "conformance", "document", "profile", "transaction", "history", "create", "read", "update", "delete", "vread", "resolve"]
                .forEach((v) => {
                    this[v] = (args = {}) => {
                        return new Promise((resolve, reject) => {
                            args.success = resolve;
                            args.error = reject;
                            fhirClient[v](args);
                        });
                    };
                });
    
        }
    
        resolveSync() {
            return this._fhirClient.resolveSync();
        }
    }

**Comment by niquola** [comment]
Look at FHIR node module, you have to require specific adapter. We support jquery, angularjs or yui. When you require FHIR, you are trying to load node adapter with node dependencies - that's why it fails. If you need another adapter - it easily could be added ;)

**Comment by niquola** [comment]
https://github.com/FHIR/fhir.js/tree/master/src/adapters

**Comment by developer-x** [comment]
That seemed to do the trick - thanks!
