### ISSUE TITLE
Cookies behavior should be opt-in

### ISSUE THREAD

**Issue by jmandel** [FHIR/fhir.js#64]
#63 adds behavior to automatically send cookies when requesting content from third party domains. I think this is potentially dangerous behavior and we should think through security more systematically. Why? Because in many cases (e.g. when using OAuth) a client doesn't want to send cookies, and sending them would lead to confusing or undefined behavior (and that's bad in the security domain).

We already have security middlewares for OAuth (for sure) and http basic (I think).

@arcticShadow @niquola We should add one for cookies, too, so unless that's enabled, no cookies are sent to *any* domain. Enabling cookies should add a property to the http options (e.g. "withCredentials: true",   as in https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials). 

To support this, adapters will need to read that field and set the appropriate value on all  requests they issue.

Also let me say @arcticShadow: protecting a FHIR API with cookies and CORS in general strikes me as a dangerous proposition, and unless you get all the details precisely correct (https only, no JS, csrf tokens, zero xss bugs...) it's very easy to find yourself in a situation where you hand over full API access to an attacker.

**Comment by arcticShadow** [comment]
@jmandel I completely agree regarding the poor decision on using cookies for authentication. 

Unfortunately, I have what I have to work with. We have a 2 layer system, the top layer has oauh and other nice bits, and the bottom (older) layer has simpler methods of authentication.

I can assure you though, we have as many bases covered as possible with regards to httponly, secure, csrf, xss etc.

I wasn't aware of the security middleware. That sounds like it will be an awesome way to meet the needs of the problem. And I 100% agree that It's not safe to stay how it is. (I wasn't thinking terribly much when I put together the P.R. I was more focused on solving a small problem that was about to become a huge problem)

**Comment by niquola** [comment]
Ups @jmandel, i thought, described behavior (i.e. sending cookies to other domains) is impossible with modern browsers :(. Shame on me. Let's move this into optional middle-ware.

**Comment by arcticShadow** [comment]
I've been looking at how to achieve this while i had some free time this morning. 

I dont think I understand how the middleware concept is working. 

i.e. I set something in my config indicating i want to use credentials. The cookies middleware checks for that variable, and adds something to the config, that the adapter looks for and uses..... This sounds silly so I assume it's not right (I tried to copy the bearer/basic auth logic)

Is it possible to apply middleware in a consuming project? What would an example of this look like?

**Comment by jmandel** [comment]
Hmm, your "silly" description sounds right -- what's not working?

**Comment by arcticShadow** [comment]
I havn't actually tried to implement the silly idea yet. I don't see the point in adding middleware if I can pass options directly to the adapter options via config.

**Comment by jmandel** [comment]
Ah, I see. For the basic + OAuth middleware behavior, the advantage is that
http options objects are updated in one place, across all adapters, and the
adapters just see the updated options. The current adapter API doesn't
exactly make "config" visible to the adapter.http function at runtime
(though you could always put it in a closure so it was visible...).

The main advantage to putting the cookie flag in auth.js is that it would
consolidate all three auth-related features into a single "auth" middleware
file, so the related code is all in one place; it feels more like a
systematic approach. But I have no strong opinion on this part.

  -J
