### ISSUE TITLE
read method sporadically removing an identifier

### ISSUE THREAD

**Issue by markgillnz** [FHIR/fhir.js#75]
Calling the read on the patient resource method with an id (e.g. /Patient/23) sporadically removes an identifier from the response resource.

This has been noticed from querying data from a third-party resource directly via Postman and through fhir.js. It was first noticed using version 0.0.13.

**Comment by jmandel** [comment]
Thsnks for the report. Can you help clarify what you're seeing? If you're seeing a problem suing POSTman (i.e without fhir.js) then its doest sound like a problem in fhir.js. What FHIR server are you seeing this behavior with? Can you provide a specific API call that returns inconsistent results?

**Comment by markgillnz** [comment]
Hi jmandel, we are not seeing any problem with postman, nor using fhir.js search, but we are seeing an issue with the read method. We are trying to integrate with Oridashi communicating with a local version of Medical Director, which contains an IHI identifier for the patient, amongst other valid identifiers.

Performing the API call /patient/23 with read results in a different patient resource than the call /patient?_id=23 with search. The difference being that the IHI identifier is not present in the read API call (discounting the differences between returning a resource vs a bundle).

**Comment by jmandel** [comment]
I'm struggling to understand whether you're seeing a problem with fhir.js
or with a specific server. Could you please clarify? A failing example
(with complete URL or code) would probably help.

**Comment by markgillnz** [comment]
We are using a local server for testing provided by Oridashi but the data is the same as that on the Oridashi demo website (http://oridashi.com.au/site/demo.html) so you may be able to use that to test against.
Note our data includes an additional IHI identifier which is not present in the Oridashi demo data and it appears to be this identifier which is sometimes being removed by the read method.

I have attached our responses for two patients (https://localhost:8080/Patient/23 or https://localhost:8080/Patient?_id=23 and https://localhost:8080/Patient/21 or https://localhost:8080/Patient?_id=21)

For patient 21 (Penny Anderson) Postman, fhirjs.read and fhirjs.search all return the same resource.
For patient 23 (Maureen Andrews) Postman and fhirjs.search return the same resource but fhirjs.read is missing the IHI identifier.

I see that patient 21 has two identifiers but patient 23 has three. Could it be that fhirjs.read will only return  the first two identifiers instead of all of them?

[Responses.zip](https://github.com/FHIR/fhir.js/files/324455/Responses.zip)

**Comment by oridashi** [comment]
I have now added this type of identifier in for this patient on the Oridashi demo server http://md.oridashi.com.au/Patient/23 so can see the content on live server - can't see a server problem or format problem but let me know...

**Comment by oridashi** [comment]
Have pushed copy to Brian's server also http://sqlonfhir-dstu2.azurewebsites.net/fhir/Patient/5064112ba4cf46bbbd30de16860c6bfe check if same behaviour from there...

**Comment by arcticShadow** [comment]
I've setup sample code, that fails to reproduce the issue, based on http://md.oridashi.com.au/Patient/23
https://tonicdev.com/5768a199e4f265130002448e/5768a199e4f265130002448f

**Comment by oridashi** [comment]
What browser are you in; seems to work fine in Chrome for me?

**Comment by arcticShadow** [comment]
The above tonicdev sample was run in Chrome, and Failed to reproduce the issue. 

I have used the following code snippet - which is not specific to our project, but is specfically using Systemjs to load fhir.js.

It has been run in the chrome console, and the purpose was to run on a machine that has access to the hiasobi adapter, and test it. 

This code also fails to reproduce the issue.

```javascript
System.import("fhir.js/src/adapters/native").then(function(fhirjs){
var fhirclient = fhirjs({
 // baseUrl: 'http://md.oridashi.com.au',   
    baseUrl: 'https://127.0.0.1:8298',
      auth: {
  //  Oridashi https endpoint auth credentials
    user: 'samples',
    pass: '67763F1A6A6146D9B5ADA858',
  },
  debug:false,
});
var id = '23';
fhirclient.search({
    type: 'Patient',
    query: {
      _id: id,
    }
}).then(function(searchResponse ){
  console.log("Search", searchResponse.data.entry[0].resource.identifier);
});


var readResponse = fhirclient.read({type: 'Patient', id: id}).then(function(readResponse){
  console.log("Read", readResponse.data.identifier);
});
});
```

**Comment by markgillnz** [comment]
I have now seen the issue when using the search method too so am not convinced the issue lies with fhir.js but possibly with our application setup. I will continue to investigate and hopefully close this issue as a non-issue.

**Comment by markgillnz** [comment]
This issue has now been resolved and identified as no issue with fhir.js.
This issue can be closed.

**Comment by jmandel** [comment]
Thanks for following up!
