### ISSUE TITLE
Firefox ESR errors before and prevents next page calls

### ISSUE THREAD

**Issue by danwhitfield** [FHIR/fhir.js#94]
I'm seeing an issue where a 'nextPage' request is failing in Firefox ESR (45.8.0) with the error: "HEAD or GET Request cannot have a body.". This appears to be because the native adapter adds a body property to the fetch options regardless of whether or not it is set: https://github.com/FHIR/fhir.js/blob/master/src/adapters/native.js#L48. 

I have tried locally wrapping this setting of the body in a condition to check if data is null or not and that then works:

```
if (fetchOptions.data != null) {
    // data neeeds to map to body
    fetchOptions.body = fetchOptions.data;
}
```
I assume that when fetch makes the request it just blindly sets the body for the request and as this is a GET request (for next page), Firefox ESR can't handle a GET with a body set. I am not 100% sure on that though.

The actual next page GET request is never even fired, it errors before that.

**Comment by arcticShadow** [comment]
@niquola Is there anything stopping a publish of fhir.js, and closing this issue?

**Comment by niquola** [comment]
done - please, test it

**Comment by danwhitfield** [comment]
Tested, works great thanks!
