### ISSUE TITLE
_has reverse chaining Query Object

### ISSUE THREAD

**Issue by vsocrates** [FHIR/fhir.js#97]
Hi,

I am using the SMART on FHIR JS client, which uses this as the backend and I can't use the reverse chaining keyword `_has` found at the following URL: [https://www.hl7.org/fhir/search.html#has](url). 

A properly formed URL that uses `has` looks like: [http://fhirtest.uhn.ca/baseDstu3/Patient?_has:Observation:patient:&_elements=id](url) but I haven't found a way in fhir.js to include the `:` after the `_has` or include multiple chained `:` using the MongoDB syntax shown in the README. 

The closest I've gotten is: [http://fhirtest.uhn.ca/baseDstu3/Patient?_has=Observation%3Apatient%3A&_elements=id](url) using the QueryObject: `{_has:["Observation:patient:"], _elements: [["id"]]}`

If there is a way to do this, please let me know. Thank you!

**Comment by mike1pol** [comment]
In v0.1.0 added `$has` operator
